In [16]:
from tensorflow.keras.preprocessing.text import one_hot

In [17]:
# Sentences
sent =[ 'the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'I am a good boy',
       'I am a good developer',
       'understand the meaning of words',
       'your video are good',
]

In [18]:
# Define the vocabulary size
voc_size = 10000

In [19]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your video are good']

In [20]:
## One hot representantion
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4624, 5127, 2379, 4624],
 [4624, 5127, 2379, 5598],
 [4624, 8400, 2379, 805],
 [8124, 7577, 4211, 8476, 557],
 [8124, 7577, 4211, 8476, 2289],
 [8495, 4624, 7675, 2379, 1956],
 [1004, 9681, 6772, 8476]]

In [21]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [30]:
# Pad sequences to a fixed length using pre-padding
sent_length = 8   # longest sentence has 5 words; 8 is just a chosen fixed length
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4624 5127 2379 4624]
 [   0    0    0    0 4624 5127 2379 5598]
 [   0    0    0    0 4624 8400 2379  805]
 [   0    0    0 8124 7577 4211 8476  557]
 [   0    0    0 8124 7577 4211 8476 2289]
 [   0    0    0 8495 4624 7675 2379 1956]
 [   0    0    0    0 1004 9681 6772 8476]]


In [26]:
## Feature representation
dim = 10 # Dimension

In [31]:
from tensorflow.keras.layers import Input, Embedding
from tensorflow.keras.models import Sequential

model = Sequential([
    Input(shape=(sent_length,)),
    Embedding(input_dim=voc_size, output_dim=dim),
])
model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.predict(embedded_docs) # Every words will be represented by 10 dimension

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[[ 3.7792016e-02, -7.6610819e-03,  2.0208929e-02,  4.6219651e-02,
          6.9829114e-03, -2.1257568e-02, -3.8825594e-02,  2.6579831e-02,
          9.2493892e-03,  2.1728087e-02],
        [ 3.7792016e-02, -7.6610819e-03,  2.0208929e-02,  4.6219651e-02,
          6.9829114e-03, -2.1257568e-02, -3.8825594e-02,  2.6579831e-02,
          9.2493892e-03,  2.1728087e-02],
        [ 3.7792016e-02, -7.6610819e-03,  2.0208929e-02,  4.6219651e-02,
          6.9829114e-03, -2.1257568e-02, -3.8825594e-02,  2.6579831e-02,
          9.2493892e-03,  2.1728087e-02],
        [ 3.7792016e-02, -7.6610819e-03,  2.0208929e-02,  4.6219651e-02,
          6.9829114e-03, -2.1257568e-02, -3.8825594e-02,  2.6579831e-02,
          9.2493892e-03,  2.1728087e-02],
        [-3.1070530e-02, -9.4682798e-03,  3.7204687e-02, -2.1893954e-02,
          3.2499801e-02,  3.2616522e-02, -1.7011058e-02,  2.9808905e-02,
         -3.0763233e-02,  4.4207666e-02],
        [-1.7043937e-02,  5.9974194e-03,  4.8572149e-02, -3.

In [33]:
embedded_docs[0]

array([   0,    0,    0,    0, 4624, 5127, 2379, 4624], dtype=int32)